### ISSUE TITLE
E2E Testing Nakamoto Checklist

### ISSUE THREAD

**Issue by ASuciuX** [stacks-network/stacks-core#5133]
<details>
  <summary>Questions</summary>
  
- Does follower validate state/blocks? YES
- When do tenure extends happen? Do they have coinbase (or only fee promise)?
    - Current: Only when sorition is missed (burn block with no stacks block commit op)
    - Future: Long period / or miner failed to propose
- What are chunks? (What do they contain? Does miner remember what they proposed (for a chunk to be created)?)
- If the majority of miners are acting maliciously while a minority follow the correct procedures, once the mining winner is selected, will the correct block still be validated on-chain even if the winner belongs to the minority? Or could the malicious majority manipulate the data and falsely claim they’ve won the block?
- If Nakamoto forks (malicious majority)? Which forks is followed by others?
- Are miners ever penalized?
    - What happens if miner only submits nakamoto coinbase (and no next fast blocks)?
- Are signers ever penalized?
    - Field in block header, which signers are behaved. If signers’ bit is zero, stacking slots will be burned instead. (punish slow signers?)
- Can you stack using bitcoin transactions? This should be possible, otherwise total failure if no Stacks blocks in prepare phase or the current 30%+1 signer is malicious and doesn’t sign any transactions
- Is this the typical process? Yes. The miner writes data to the stackerdb, signers read from it, then communicate with their nodes (mostly followers) to validate the data, and finally send back chunks through the stackerdb to the miner.
- Does a miner node always need a signer? No

- When the bitcoin transaction for miners have to be sent in the flow
      btc.           | 1000 
      stx.   300. |  301 302
      miner (that is not the winner of this tenure) submits after seeing 301 for 1001
      miner that is the winner of this tenure can submit it before 301 is anchored as it knows it (will not influence the overall flow with anything) 
      301 tenure change tx so i commit to that in my bitcoin transaction

</details>

## Chaos Testing

*Anything that can go down will go down*

- Swallowing communication (%)
    - Miner<>Signer (RPC)
    - P2P<>Followers<>Miners
    - Solution: Docker composed into regtest-env
        - Metric: Block height; Cycles with rewards; Number/% of stuck followers;
- Censoring Stacks burn ops
    - “Flash blocks” or censorship
    - Metric:
        - Do signers recover? ()
        - How many censored blocks until
    - Unlikely: Entire prepare phase censored?
- Speed
    - How fast to bitcoin/nakamoto blocks have to be to break the system?
    - Unusually long bitcoin block; what happens? How many extends?

## Forks

**Stories**

- [x] When a new burn block is mined; fast blocks should stop being invalid (and potentially rolled back if fast blocks where signed after new burn block) (Integration)
- [x] Miner ignores latest nakamoto blocks; instead proposes “fork” nakamoto block; what will other signers do? (Integration)
    - Can the majority decide to fork nakamoto blocks? Do minority follower & signers the fork or consider this bad / do they recover?
- [x] What happens if 40% refuse to sign? Nothing will happen.

## Miners

*Less important? They’ll figure out how to restart. Someone else will take over.*

**Stories**

- [ ] Other miner can’t propose on behalf of current tenure miner. Is the sig/key checked? [This unit test](https://github.com/stacks-network/stacks-core/blob/develop/stacks-signer/src/tests/chainstate.rs#L141-L155) is enough or want it more specifically? (eg. 2 miners with different keys, minerA proposes a block using minerB key and is rejected because signature mismatch )
- [ ] Signer doesn’t respond to proposal (delayed by 2 minutes); Miner in the meantime tries new proposal(s); Instead signer later responds with “old” valid proposal acceptance; Does miner recover and continue off of “valid” chain? (Integration/Unit)
    - Signer broadcasts (which makes it easier, and miner *should* recover by receiving new block over P2P)
- [ ] If signers rollover (new cycle, different signers); Miner shouldn’t accept sigs from “old”/previous set of signers; (Integration)
    - The tenure-change locks in the chain tip
- [ ] Signer (or anybody (not on same network)) sends invalid chunk(/block) to miner? What happens? (Integration)
- [ ] Is it tested the way miners are intended to run when the epoch upgrade happens on the X selected block height. - https://github.com/stacks-network/stacks-core/issues/5127
- [ ] Would temporary network/communication issues on the miner/signer disrupt their behaviour and need to be restarted? https://github.com/hirosystems/stacks-e2e-testing/issues/64
- [ ] Transaction that can't be added to the mempool is anchored by the miner in valid block - https://github.com/stacks-network/stacks-core/issues/5129
- [ ] Could a lot of small miners, each spending 0.1$ worth of btc per block, do anything malicious to congest the communication/network?  https://github.com/stacks-network/stacks-core/issues/5131

## Signers

**Stories**

- [x] Signer rejects invalid proposal from miner - [unit test](https://github.com/stacks-network/stacks-core/blob/develop/stacks-signer/src/tests/chainstate.rs#L126) + [integration test](https://github.com/stacks-network/stacks-core/blob/2be69cbf744ac339476362a3fb281257c9e1bebc/testnet/stacks-node/src/tests/signer/v0.rs#L433)
- [ ] ~~Miner proposes bad/invalid block; Signer should NOT accept it; (Unit/Integration)~~
    - 🚧 /validate is RPC called by signer before signing
        - [the integration hits from here](https://github.com/stacks-network/stacks-core/blob/2be69cbf744ac339476362a3fb281257c9e1bebc/testnet/stacks-node/src/tests/signer/v0.rs#L482) with UnknownParent
        - [ ] TODO: add the other possible cases [from here](https://github.com/stacks-network/stacks-core/blob/2be69cbf744ac339476362a3fb281257c9e1bebc/testnet/stacks-node/src/tests/signer/v0.rs#L39)
        - [ ] ~~If majority (maliciously) signs/approves invalid block; the fair minority should still work off of “valid” chain? They would have to stall as there are not enough signatures (Integration)~~
- [x] Signer can only write to their own allotted StackerDB slot (Unit)
    - [this test](https://github.com/stacks-network/stacks-core/blob/develop/stackslib/src/chainstate/stacks/boot/signers_tests.rs#L284-L345) only checks they have their own slot, not that they run on it
    - [this test](https://github.com/stacks-network/stacks-core/blob/2be69cbf744ac339476362a3fb281257c9e1bebc/libstackerdb/src/tests/mod.rs#L26) checks the write through public key check
    - If chunk is taken; node will refuse the chunk
- [ ] 🚧 Signer tries to write too frequently to the StackerDB. (Unit) https://github.com/stacks-network/stacks-core/issues/5122
- [ ] Prepare phase missed stalls system — unrecoverable
  - Question: can you stack using bitcoin transactions? this should be done, otherwise total failure if no stacks blocks in prepare phase or the signer is malicious and doesn’t sign any transactions
- [ ] How can the stackerdb be corrupted/stalled?
  - Post invalid chunk somehow? (Signers) - try sql injection
  - Invalid chain state? (Node; Unit test)
  - P2P stalls (Node; Unit test) 
  
## Tenures

**Stories**

- [ ] Miner proposes many tenure-extends; (Integration)
    - Signers will reject
    - Signers listen to: StackerDB events; proposal events; burn block events

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
